Repository bunderLikeLion/sellon_backend, pull requests merged in 2022-07, with the labels that each got.

#2 django startproject (도커라이즈 X)
  .gitignore
  .pre-commit-config.yaml
  README.md
  sample_env
  setup.cfg
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/__init__.py
  webapp/config/asgi.py
  webapp/config/settings/base.py
  webapp/config/settings/development.py
  webapp/config/settings/production.py
  webapp/config/settings/test.py
  webapp/config/urls.py
  webapp/config/wsgi.py
  webapp/manage.py
Labels: 프로젝트세팅

#5 dockerize, docker-compose
  db/initial_setup.sql
  docker-compose.production.yml
  docker-compose.yml
  sample_env
  setup.cfg
  webapp/Dockerfile
  webapp/Dockerfile.production
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/settings/base.py
  webapp/config/settings/development.py
  webapp/config/settings/production.py
  webapp/docker-entrypoint.production.sh
  webapp/docker-entrypoint.sh
Labels: 프로젝트세팅

#6 nginx 세팅
  docker-compose.production.yml
  docker-compose.yml
  nginx/Dockerfile
  nginx/Dockerfile.production
  nginx/docker-entrypoint.sh
  nginx/nginx.conf
  nginx/nginx.production.conf
  nginx/wait-for-it.sh
Labels: 프로젝트세팅

#11 djangorestframework 설치
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/settings/base.py
Labels: 프로젝트세팅

#14 dj-rest-auth를 이용한 기본 user api / drf_yasg를 이용한 API 문서 세팅 / static, media serving
  .gitignore
  README.md
  docker-compose.production.yml
  docker-compose.yml
  nginx/nginx.conf
  nginx/nginx.production.conf
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/user/__init__.py
  webapp/user/admin.py
  webapp/user/apps.py
  webapp/user/migrations/0001_initial.py
  webapp/user/migrations/__init__.py
  webapp/user/models.py
  webapp/user/urls.py
Labels: 프로젝트세팅

#37 product_categories 추가
  .gitignore
  webapp/product/migrations/0004_productcategory_product_product_category.py
  webapp/product/migrations/0005_alter_productcategory_display_order_and_more.py
  webapp/product/models/__init__.py
  webapp/product/models/product.py
  webapp/product/models/product_category.py
Labels: :green_book: In review

#38 django-guid 추가 및 설정
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/settings/base.py
  webapp/config/settings/development.py
Labels: :green_book: In review

#49 feat: product viewset 구현
  webapp/config/pagination.py
  webapp/config/urls.py
  webapp/product/serializers.py
  webapp/product/urls.py
  webapp/product/views.py
Labels: enhancement

#50 feat: 다른 User 정보를 조회할 수 있는 API
  webapp/user/serializers/user_abstract_serializer.py
  webapp/user/urls.py
  webapp/user/views.py
Labels: enhancement

#51 ProductCategory-ListAPIView
  webapp/config/models.py
  webapp/product/serializers.py
  webapp/product/urls.py
  webapp/product/views.py
Labels: :green_book: In review

#54 Product group model
  webapp/auction/__init__.py
  webapp/auction/admin.py
  webapp/auction/apps.py
  webapp/auction/migrations/0001_initial.py
  webapp/auction/migrations/__init__.py
  webapp/auction/models/__init__.py
  webapp/auction/models/auction.py
  webapp/auction/tests.py
  webapp/auction/urls.py
  webapp/auction/views.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/product/migrations/0007_productgroup_productgroupitem.py
  webapp/product/models/__init__.py
  webapp/product/models/project_group.py
  webapp/product/models/project_group_item.py
Labels: :green_book: In review

#57 chore: install django-jazzmin
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/settings/base.py
Labels: 프로젝트세팅

#60 feat: Dealing model
  webapp/__init__.py
  webapp/config/settings/base.py
  webapp/dealing/__init__.py
  webapp/dealing/admin/__init__.py
  webapp/dealing/admin/dealing.py
  webapp/dealing/apps.py
  webapp/dealing/migrations/0001_initial.py
  webapp/dealing/migrations/__init__.py
  webapp/dealing/models/__init__.py
  webapp/dealing/models/dealing.py
  webapp/dealing/serializers/serializers.py
  webapp/dealing/tests.py
  webapp/dealing/views.py
  webapp/product/models/__init__.py
  webapp/product/models/product_group.py
  webapp/product/models/product_group_item.py
Labels: enhancement

#64 Auction crud api
  webapp/auction/admin.py
  webapp/auction/admin/__init__.py
  webapp/auction/admin/auction.py
  webapp/auction/permissions.py
  webapp/auction/serializers/__init__.py
  webapp/auction/serializers/auction_serializers.py
  webapp/auction/urls.py
  webapp/auction/views.py
  webapp/config/serializers/__init__.py
  webapp/config/serializers/integer_choice_field.py
  webapp/file_manager/serializers/image_serializer.py
  webapp/product/admin/__init__.py
  webapp/product/admin/product_category.py
  webapp/product/models/product.py
  webapp/product/serializers/__init__.py
  webapp/product/serializers/product_abstract_serializer.py
  webapp/product/serializers/product_category_serializer.py
  webapp/product/serializers/product_serializer.py
Labels: :green_book: In review

#69 auction에 거래 방법 추가
  webapp/auction/migrations/0002_auction_dealing_type.py
  webapp/auction/migrations/0003_alter_auction_dealing_type.py
  webapp/auction/models/auction.py
  webapp/auction/serializers/auction_serializers.py
Labels: :green_book: In review
