Repository bunderLikeLion/sellon_backend, pull requests merged in 2022-08, with the labels that each got.

#74 chore: auction에 product_id로 상품 추가
  webapp/auction/models/auction.py
  webapp/auction/permissions.py
  webapp/auction/serializers/auction_serializers.py
  webapp/auction/views.py
  webapp/config/serializers/integer_choice_field.py
Labels: :green_book: In review

#75 Dealings today completed count
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/dealing/serializers/__init__.py
  webapp/dealing/serializers/dealing_serializer.py
  webapp/dealing/urls.py
  webapp/dealing/views.py
  webapp/product/admin/__init__.py
  webapp/product/admin/product_group.py
Labels: :green_book: In review

#78 feat : Message model 및 admin 구현
  webapp/config/settings/base.py
  webapp/message/__init__.py
  webapp/message/admin/__init__.py
  webapp/message/admin/message.py
  webapp/message/apps.py
  webapp/message/migrations/0001_initial.py
  webapp/message/migrations/__init__.py
  webapp/message/models/__init__.py
  webapp/message/models/message.py
  webapp/message/serializers/__init__.py
  webapp/message/tests.py
  webapp/message/views.py
Labels: :green_book: In review

#76 fix: product quality choices lang to eng
  webapp/product/migrations/0009_alter_product_quality.py
  webapp/product/migrations/0010_alter_product_quality.py
  webapp/product/models/product.py
Labels: :green_book: In review

#77 Django counter field
  webapp/auction/__init__.py
  webapp/auction/apps.py
  webapp/auction/migrations/0004_auction_product_groups_count.py
  webapp/auction/models/auction.py
  webapp/auction/signals/product_group_signal.py
Labels: :green_book: In review

#84 feat: 내가 제시한 물건 (product_groups/my/?auction_id=) 확인 기능
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/product/serializers/__init__.py
  webapp/product/serializers/product_group_serializer.py
  webapp/product/urls/product.py
  webapp/product/urls/product_groups.py
  webapp/product/views.py
Labels: enhancement, :green_book: In review

#90 feat: interested-auction model 및 admin 구현
  webapp/auction/admin/__init__.py
  webapp/auction/admin/interested_auction.py
  webapp/auction/migrations/0004_interestedauction.py
  webapp/auction/models/__init__.py
  webapp/auction/models/interested_auction.py
Labels: enhancement, :green_book: In review

#71 feat: product_group crud
  setup.cfg
  webapp/auction/admin/auction.py
  webapp/auction/migrations/0004_alter_auction_end_at.py
  webapp/auction/migrations/0005_merge_20220802_0111.py
  webapp/auction/migrations/0006_remove_auction_deleted_at.py
  webapp/auction/migrations/0007_auction_title.py
  webapp/auction/migrations/0008_merge_0004_interestedauction_0007_auction_title.py
  webapp/auction/models/auction.py
  webapp/auction/permissions.py
  webapp/auction/serializers/auction_serializers.py
  webapp/auction/signals/product_group_signal.py
  webapp/auction/urls.py
  webapp/auction/views.py
  webapp/config/exceptions/__init__.py
  webapp/config/exceptions/handler.py
  webapp/config/models.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/dealing/migrations/0002_remove_dealing_deleted_at.py
  webapp/dealing/models/dealing.py
  webapp/product/admin/product.py
  webapp/product/admin/product_group.py
  webapp/product/apps.py
  webapp/product/migrations/0011_productgroup_products.py
  webapp/product/migrations/0012_remove_productcategory_deleted_at_and_more.py
  webapp/product/migrations/0013_productgroup_unique_product_group_in_auction_by_user.py
  webapp/product/models/product.py
  webapp/product/models/product_category.py
  webapp/product/models/product_group.py
  webapp/product/models/product_group_item.py
  webapp/product/permissions.py
  webapp/product/serializers/product_abstract_serializer.py
  webapp/product/serializers/product_group_serializer.py
  webapp/product/serializers/product_serializer.py
  webapp/product/signals/__init__.py
  webapp/product/signals/product_group_item_signals.py
  webapp/product/urls/product.py
  webapp/product/urls/product_group.py
  webapp/product/urls/product_groups.py
  webapp/product/views.py
  webapp/product/views/__init__.py
  webapp/product/views/product_category_list_api_view.py
  webapp/product/views/product_group_view_set.py
  webapp/product/views/product_view_set.py
  webapp/user/models.py
Labels: enhancement, :green_book: In review

#96 feat: product 이미지 여러개 올리기
  webapp/auction/migrations/0005_merge_20220802_2107.py
  webapp/file_manager/admin/__init__.py
  webapp/file_manager/admin/product_image.py
  webapp/file_manager/migrations/0002_productimage_delete_imaging.py
  webapp/file_manager/models/__init__.py
  webapp/file_manager/models/imaging.py
  webapp/file_manager/models/product_image.py
  webapp/file_manager/urls.py
  webapp/product/migrations/0011_product_images.py
  webapp/product/models/product.py
  webapp/product/serializers/product_serializer.py
Labels: :green_book: In review

#103 fix: 프론트 요청으로 pagination 수정
  webapp/config/pagination.py
  webapp/config/settings/base.py
Labels: :green_book: In review

#110 validation 순서 조정
  webapp/auction/models/auction.py
Labels: :bug: bug

#112 Product categories
  webapp/config/urls.py
  webapp/product/urls/product.py
  webapp/product/urls/product_categories.py
  webapp/product/views/__init__.py
  webapp/product/views/product_categories_view.py
Labels: enhancement, :green_book: In review

#116 feat: [get] /products/ OrderFilter
  webapp/product/views/product_view_set.py
Labels: enhancement, :green_book: In review

#120 feat: interested auction api
  webapp/auction/migrations/0010_interestedauction_unique_interested_auction_by_user.py
  webapp/auction/models/interested_auction.py
  webapp/auction/serializers/__init__.py
  webapp/auction/serializers/interested_auction_serializers.py
  webapp/auction/urls.py
  webapp/auction/views/__init__.py
  webapp/auction/views/interested_auction_view_set.py
  webapp/config/exceptions/handler.py
Labels: enhancement, :green_book: In review

#123 Product groups
  webapp/auction/admin/auction.py
  webapp/product/models/product_group.py
  webapp/product/serializers/product_group_serializer.py
Labels: :green_book: In review

#122 feat: csrf 토큰 인증 해제
  webapp/config/authentications.py
  webapp/config/settings/base.py
Labels: :green_book: In review

#128 fix: 옥션 삭제 시 product_groups 의 product status 가 hidden 으로 바뀌지 않던 에러 해결
  webapp/auction/models/auction.py
  webapp/auction/signals/product_group_signal.py
  webapp/product/migrations/0017_alter_productgroup_auction.py
  webapp/product/migrations/0018_alter_productgroup_auction.py
  webapp/product/models/product.py
  webapp/product/models/product_group.py
Labels: :bug: bug, :green_book: In review

#126 Add django silk
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/settings/development.py
  webapp/config/urls.py
Labels: :green_book: In review

#139 User evalution api
  webapp/config/exceptions/handler.py
  webapp/dealing/admin/__init__.py
  webapp/dealing/admin/dealing_evaluation.py
  webapp/dealing/migrations/0005_dealingevaluation_and_more.py
  webapp/dealing/models/__init__.py
  webapp/dealing/models/dealing_evaluation.py
  webapp/dealing/permissions.py
  webapp/dealing/serializers/dealing_evaluation_serializer.py
  webapp/dealing/urls.py
  webapp/dealing/views/__init__.py
  webapp/dealing/views/dealing_evaluation_view.py
  webapp/user/models/__init__.py
  webapp/user/models/user.py
  webapp/user/views/__init__.py
  webapp/user/views/user_view.py
Labels: :green_book: In review

#151 feat: 유저의 거래 횟수 반환 API
  webapp/user/urls.py
  webapp/user/views/user_view.py
Labels: enhancement, :green_book: In review

#155 feat: statistic 앱 추가 및 이달의 거래왕 필터 설정
  webapp/config/urls.py
  webapp/statistic/__init__.py
  webapp/statistic/admin.py
  webapp/statistic/apps.py
  webapp/statistic/migrations/__init__.py
  webapp/statistic/models.py
  webapp/statistic/tests.py
  webapp/statistic/urls.py
  webapp/statistic/views.py
  webapp/user/views/__init__.py
Labels: :green_book: In review

#168 fix: popular 경매에서 끝난 경매는 제외하고 가져옴
  webapp/auction/models/auction.py
Labels: :green_book: In review

#170 feat: fk인 필드를 admin 에서 linkify 로 감싸서 렌더링
  webapp/auction/admin/interested_auction.py
  webapp/dealing/admin/dealing.py
  webapp/product/admin/product.py
  webapp/product/admin/product_group.py
Labels: :green_book: In review

#172 feat: image admin 에서 이미지 미리보기로 보이게 하기
  webapp/Pipfile
  webapp/Pipfile.lock
  webapp/config/settings/base.py
  webapp/file_manager/admin/image.py
  webapp/file_manager/models/image.py
Labels: enhancement

#178 feat: GET: /dealings/ 와 GET: /dealings/:id/ 에 평가 여부 추가
  webapp/dealing/migrations/0006_alter_dealingevaluation_dealing.py
  webapp/dealing/models/dealing_evaluation.py
  webapp/dealing/serializers/dealing_serializer.py
Labels: :green_book: In review

#179 feat: admin에서 list_display 첫 번째 요소에 id
  webapp/auction/admin/interested_auction.py
Labels: :green_book: In review

#177 feat: /auctions/my/ 에서 내 옥션만 확인 가능
  webapp/auction/urls.py
  webapp/auction/views/__init__.py
  webapp/auction/views/auction_view_set.py
  webapp/auction/views/my_auction_api_view.py
Labels: enhancement, :green_book: In review

#193 feat: admin 에서 completed-dealings-count 초기화 할 수 있는 액션 생성
  webapp/user/admin.py
Labels: :green_book: In review

#194 feat: 옥션 유찰 시 product와 product_group을 hidden 상태로 변경
  webapp/auction/admin/auction.py
Labels: :green_book: In review

#195 fix: user admin 에서 썸네일 안 보이도록 수정
  webapp/user/admin.py
Labels: :green_book: In review
